exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/lindh/lindh.github.io

title: Donghui Lin, Ph.D, Associate Professor
description: Donghui Lin's Homepage
